"""
Project Lumi — first-run setup wizard.

Run directly:
    uv run python scripts/setup_wizard.py [--yes]

Or via the main entry point:
    python main.py --setup [--yes]

Exit codes:
    0 — setup complete; all required paths are present.
    1 — model file is missing and the user declined to provide a path
        (or --yes was given and no path could be resolved automatically).
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Optional

# ---------------------------------------------------------------------------
# Model catalogue
# ---------------------------------------------------------------------------

KNOWN_MODELS = [
    {
        "name": "phi-3.5-mini (recommended, 2.3 GB)",
        "filename": "phi-3.5-mini-instruct.Q4_K_M.gguf",
        "url": None,  # user must download manually from Hugging Face
        "sha256": None,
    },
    {
        "name": "custom (enter path manually)",
        "filename": None,
        "url": None,
        "sha256": None,
    },
]

# Directories that must exist before Lumi can run.
REQUIRED_DIRS = [
    "models/llm",
    "data",
    "eval_results",
]

# Default config file path (relative to CWD = repo root).
_DEFAULT_CONFIG = "config.yaml"


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _read_model_path_from_config(config_path: str) -> str:
    """Parse config.yaml and return the llm.model_path value.

    Falls back to the LLMConfig default ("models/llm/phi-3.5-mini.gguf")
    when the file is absent, unreadable, or the key is missing.
    """
    default = "models/llm/phi-3.5-mini.gguf"
    try:
        text = Path(config_path).read_text(encoding="utf-8")
    except OSError:
        return default

    # Quick regex parse — avoids importing PyYAML so this works even when
    # the venv is not fully set up.
    match = re.search(r"^\s*model_path\s*:\s*(.+)$", text, re.MULTILINE)
    if not match:
        return default

    # There may be multiple model_path keys (llm, tts, vision).  We want the
    # one inside the [llm] section.  Walk the lines to find the first
    # model_path that appears after an "llm:" section header.
    lines = text.splitlines()
    in_llm = False
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("llm:"):
            in_llm = True
            continue
        # A new top-level section (no leading spaces, ends with colon) resets.
        if stripped and not line.startswith(" ") and stripped.endswith(":"):
            in_llm = False
            continue
        if in_llm and stripped.startswith("model_path:"):
            value = stripped.split(":", 1)[1].strip()
            return value

    # Fallback: return the very first model_path match found.
    return match.group(1).strip()


def _write_model_path_to_config(config_path: str, new_path: str) -> None:
    """Update (or append) llm.model_path in config.yaml.

    Uses simple string manipulation to preserve all YAML comments.
    If the llm section exists and contains a model_path key, that line is
    replaced in-place.  Otherwise the entire config is rewritten with the
    llm.model_path key set via a brute-force append (unusual case).
    """
    cfg_file = Path(config_path)
    if not cfg_file.exists():
        # Create a minimal config file.
        cfg_file.write_text(
            f"# Project Lumi — generated by setup wizard\nllm:\n  model_path: {new_path}\n",
            encoding="utf-8",
        )
        return

    text = cfg_file.read_text(encoding="utf-8")
    lines = text.splitlines(keepends=True)
    in_llm = False
    new_lines = []
    replaced = False

    for line in lines:
        stripped = line.strip()
        if stripped.startswith("llm:"):
            in_llm = True
        elif stripped and not line.startswith(" ") and stripped.endswith(":"):
            in_llm = False

        if in_llm and stripped.startswith("model_path:") and not replaced:
            # Preserve indentation.
            indent = len(line) - len(line.lstrip())
            new_lines.append(" " * indent + f"model_path: {new_path}\n")
            replaced = True
        else:
            new_lines.append(line)

    if not replaced:
        # Append under [llm] section if we never found model_path there.
        new_lines.append(f"\n# Added by setup wizard\nllm:\n  model_path: {new_path}\n")

    cfg_file.write_text("".join(new_lines), encoding="utf-8")


def _prompt(message: str, default: Optional[str] = None, yes: bool = False) -> str:
    """Print *message* and return user input.

    When *yes* is True, print the message and return *default* immediately
    without blocking on stdin.  If *default* is None and *yes* is True,
    return an empty string.
    """
    if yes:
        display_default = default or ""
        print(f"{message} [auto: {display_default!r}]")
        return default or ""
    if default:
        answer = input(f"{message} [{default}]: ").strip()
        return answer or default
    return input(f"{message}: ").strip()


def _ensure_dirs(base: Path) -> None:
    """Create required runtime directories under *base* if they are absent."""
    for rel in REQUIRED_DIRS:
        target = base / rel
        if not target.exists():
            target.mkdir(parents=True, exist_ok=True)
            print(f"  Created: {target}")
        else:
            print(f"  OK:      {target}")


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def run_setup(yes: bool = False, config_path: str = _DEFAULT_CONFIG) -> int:
    """Run the interactive setup wizard.

    Args:
        yes:         If True, accept all defaults without prompting (CI mode).
        config_path: Path to config.yaml.  Override in tests to use a
                     tmp_path-based file.

    Returns:
        0 on success, 1 if the LLM model file is unresolvable.
    """
    print("=" * 60)
    print("  Project Lumi — first-run setup wizard")
    print("=" * 60)
    print()

    # ------------------------------------------------------------------
    # 1. Resolve the base directory (repo root) from config_path.
    # ------------------------------------------------------------------
    base_dir = Path(config_path).resolve().parent

    # ------------------------------------------------------------------
    # 2. Create required directories.
    # ------------------------------------------------------------------
    print("Checking required directories...")
    _ensure_dirs(base_dir)
    print()

    # ------------------------------------------------------------------
    # 3. Read the current model path from config.yaml.
    # ------------------------------------------------------------------
    current_model_path = _read_model_path_from_config(config_path)
    # Resolve relative paths against base_dir.
    resolved_current = (base_dir / current_model_path).resolve()

    print(f"Configured LLM model path: {current_model_path}")
    print(f"  (Resolved: {resolved_current})")

    # ------------------------------------------------------------------
    # 4. Check whether the model file already exists.
    # ------------------------------------------------------------------
    if resolved_current.is_file():
        print(f"\n  Model file found — skipping download step.")
        final_model_path = current_model_path
    else:
        print(f"\n  Model file NOT found at configured path.")
        print()
        print("Supported models:")
        for idx, model in enumerate(KNOWN_MODELS, start=1):
            print(f"  {idx}. {model['name']}")
        print()
        print(
            "Note: Lumi does not download models automatically.\n"
            "      Download from https://huggingface.co/bartowski/Phi-3.5-mini-instruct-GGUF\n"
            "      (look for 'Phi-3.5-mini-instruct-Q4_K_M.gguf') and provide its path below."
        )
        print()

        # In --yes mode we cannot download automatically, so we fail cleanly.
        if yes:
            print(
                "ERROR: LLM model file is missing and --yes mode cannot prompt for a path.\n"
                f"       Download the model and place it at:\n"
                f"         {resolved_current}\n"
                "       Then re-run setup."
            )
            return 1

        # Interactive: ask the user to supply a path.
        user_path = _prompt(
            "Enter the full path to your GGUF model file (or press Enter to skip)",
            default="",
            yes=False,
        ).strip()

        if not user_path:
            print(
                "\nNo model path provided.\n"
                "Lumi will not be able to respond until a model is installed.\n"
                f"Place the GGUF file at: {resolved_current}"
            )
            return 1

        # Verify the supplied path exists.
        supplied = Path(user_path)
        if not supplied.is_file():
            print(
                f"\nFile not found: {user_path}\n"
                "Please verify the path and re-run setup."
            )
            return 1

        final_model_path = user_path
        print(f"  Using: {final_model_path}")

    # ------------------------------------------------------------------
    # 5. Write-back if the path changed.
    # ------------------------------------------------------------------
    if final_model_path != current_model_path:
        print(f"\nUpdating config.yaml → llm.model_path: {final_model_path}")
        _write_model_path_to_config(config_path, final_model_path)
        print("  config.yaml updated.")
    else:
        print("\nconfig.yaml is up to date.")

    # ------------------------------------------------------------------
    # 6. Final config validation summary.
    # ------------------------------------------------------------------
    print()
    print("Configuration summary:")
    print(f"  LLM model path : {final_model_path}")
    print(f"  Config file    : {config_path}")

    # ------------------------------------------------------------------
    # 7. Done.
    # ------------------------------------------------------------------
    print()
    print("=" * 60)
    print("  Setup complete.")
    print("  Run 'uv run python src/main.py' to start Lumi.")
    print("=" * 60)
    return 0


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Project Lumi — first-run setup wizard",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Exit codes:\n"
            "  0 — setup complete\n"
            "  1 — model missing and path could not be resolved\n"
        ),
    )
    parser.add_argument(
        "--yes",
        "-y",
        action="store_true",
        help="Accept all defaults without prompting (CI / non-interactive mode).",
    )
    parser.add_argument(
        "--config",
        default=_DEFAULT_CONFIG,
        help=f"Path to config.yaml (default: {_DEFAULT_CONFIG})",
    )
    args = parser.parse_args()
    sys.exit(run_setup(yes=args.yes, config_path=args.config))
